# Generated by Django 4.2.2 on 2023-07-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_user_alter_bid_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
