# Generated by Django 4.2.2 on 2023-08-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image_url_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_open',
            field=models.BooleanField(default=True),
        ),
    ]
